services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80" # Maps port 80 on the VPS to your API
    depends_on:
      - postgres
      - redis
    volumes:
      - repo_data:/path/to/delta.backend/repos # Shared storage for git clones

  worker:
    build: .
    command: python workers.py
    depends_on:
      - postgres
      - redis
    volumes:
      - repo_data:/path/to/delta.backend/repos # Shared storage for git clones

volumes:
  postgres_data:
  repo_data: # Crucial for your app!
