"""Add base and head branches to DriftEvent

Revision ID: 21fc9a321370
Revises: 645142014e4c
Create Date: 2026-02-17 03:09:19.520315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fc9a321370'
down_revision = '645142014e4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('base_branch', sa.String(), nullable=False))
    op.add_column('drift_events', sa.Column('head_branch', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_events', 'head_branch')
    op.drop_column('drift_events', 'base_branch')
    # ### end Alembic commands ###
