"""Initial Migration

Revision ID: 645142014e4c
Revises: 
Create Date: 2026-02-05 22:15:00.957304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '645142014e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('github_user_id', sa.Integer(), nullable=True),
    sa.Column('github_username', sa.String(), nullable=True),
    sa.Column('current_refresh_token_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_user_id')
    )
    op.create_table('installations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_index('idx_installations_user', 'installations', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('docs_root_path', sa.String(), nullable=True),
    sa.Column('target_branch', sa.String(), nullable=True),
    sa.Column('drift_sensitivity', sa.Float(), nullable=True),
    sa.Column('style_preference', sa.String(), nullable=True),
    sa.Column('file_ignore_patterns', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.installation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'repo_name')
    )
    op.create_table('doc_coverage_map',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('code_path', sa.String(), nullable=False),
    sa.Column('doc_file_path', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'code_path', 'doc_file_path')
    )
    op.create_index('idx_coverage_repo', 'doc_coverage_map', ['repo_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('base_sha', sa.String(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=False),
    sa.Column('check_run_id', sa.BigInteger(), nullable=True),
    sa.Column('processing_phase', sa.String(), nullable=True),
    sa.Column('drift_result', sa.String(), nullable=True),
    sa.Column('overall_drift_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('agent_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("drift_result IN ('pending', 'clean', 'drift_detected', 'missing_docs', 'error')", name='check_drift_result'),
    sa.CheckConstraint("processing_phase IN ('queued', 'scouting', 'analyzing', 'generating', 'verifying', 'completed', 'failed')", name='check_processing_phase'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drift_active_runs', 'drift_events', ['repo_id'], unique=False, postgresql_where=sa.text("processing_phase NOT IN ('completed', 'failed')"))
    op.create_table('code_changes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drift_event_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('is_code', sa.Boolean(), nullable=True),
    sa.CheckConstraint("change_type IN ('added', 'modified', 'deleted')", name='check_code_change_type'),
    sa.ForeignKeyConstraint(['drift_event_id'], ['drift_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drift_event_id', sa.UUID(), nullable=True),
    sa.Column('code_path', sa.String(), nullable=False),
    sa.Column('doc_file_path', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('drift_type', sa.String(), nullable=True),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("change_type IN ('added', 'modified', 'deleted')", name='check_finding_change_type'),
    sa.CheckConstraint("drift_type IN ('outdated_docs', 'missing_docs', 'ambiguous_docs')", name='check_start_drift_type'),
    sa.ForeignKeyConstraint(['drift_event_id'], ['drift_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift_findings')
    op.drop_table('code_changes')
    op.drop_index('idx_drift_active_runs', table_name='drift_events', postgresql_where=sa.text("processing_phase NOT IN ('completed', 'failed')"))
    op.drop_table('drift_events')
    op.drop_index('idx_coverage_repo', table_name='doc_coverage_map')
    op.drop_table('doc_coverage_map')
    op.drop_table('repositories')
    op.drop_index('idx_installations_user', table_name='installations')
    op.drop_table('installations')
    op.drop_table('users')
    # ### end Alembic commands ###
