"""Add reviewer to repositories

Revision ID: 6ea9418ff8c8
Revises: 5ada42d54b00
Create Date: 2026-03-09 11:47:39.778551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea9418ff8c8'
down_revision = '5ada42d54b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('reviewer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'reviewer')
    # ### end Alembic commands ###
