"""add is_ignored to code_changes

Revision ID: 80f75118a8ac
Revises: ef4b5b3df902
Create Date: 2026-03-01 10:37:21.385409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f75118a8ac'
down_revision = 'ef4b5b3df902'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_changes', sa.Column('is_ignored', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_changes', 'is_ignored')
    # ### end Alembic commands ###
