"""remove agent_logs col

Revision ID: 828aba75015e
Revises: b2a50fb4be80
Create Date: 2026-03-10 00:00:51.537152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '828aba75015e'
down_revision = 'b2a50fb4be80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_events', 'agent_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('agent_logs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
