"""added docs_pr_number to DriftEvent

Revision ID: 8a4b15ccb884
Revises: c1be91efd499
Create Date: 2026-03-09 03:18:52.067248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4b15ccb884'
down_revision = 'c1be91efd499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('docs_pr_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_events', 'docs_pr_number')
    # ### end Alembic commands ###
