"""add_docs_policies_to_repositories

Revision ID: a424f218f7f0
Revises: 828aba75015e
Create Date: 2026-03-10 03:10:44.173234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a424f218f7f0'
down_revision = '828aba75015e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('docs_policies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'docs_policies')
    # ### end Alembic commands ###
