"""add retry_count to drift event

Revision ID: c1be91efd499
Revises: fc4d14e97cd1
Create Date: 2026-03-08 12:24:43.100961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1be91efd499'
down_revision = 'fc4d14e97cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_events', 'retry_count')
    # ### end Alembic commands ###
