"""Updated models/ with type fixes

Revision ID: c45599433adf
Revises: 21fc9a321370
Create Date: 2026-02-17 15:50:54.697699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c45599433adf'
down_revision = '21fc9a321370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doc_coverage_map', 'last_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_events', 'processing_phase',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drift_events', 'drift_result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drift_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('installations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('repositories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('repositories', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('repositories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('repositories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('repositories', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('repositories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('installations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drift_events', 'drift_result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drift_events', 'processing_phase',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doc_coverage_map', 'last_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
