"""Deleted DocCoverapeMap Table

Revision ID: ef4b5b3df902
Revises: c45599433adf
Create Date: 2026-02-25 10:17:01.050340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef4b5b3df902'
down_revision = 'c45599433adf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_coverage_repo'), table_name='doc_coverage_map')
    op.drop_table('doc_coverage_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_coverage_map',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('repo_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('code_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('doc_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_verified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], name=op.f('doc_coverage_map_repo_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doc_coverage_map_pkey')),
    sa.UniqueConstraint('repo_id', 'code_path', 'doc_file_path', name=op.f('doc_coverage_map_repo_id_code_path_doc_file_path_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_coverage_repo'), 'doc_coverage_map', ['repo_id'], unique=False)
    # ### end Alembic commands ###
