from sqlalchemy.orm import Session

from app.models.installation import Installation
from app.models.repository import Repository
from app.models.drift import DriftEvent, DriftFinding, CodeChange
from app.services.github_api import (
    create_queued_check_run,
    create_skipped_check_run,
    create_success_check_run,
    get_commit,
)
from app.core.queue import task_queue
from app.services.drift_analysis import run_drift_analysis
from app.services.notification_service import create_notification


# Handle pr_opened webhook event
async def _handle_pr_opened(db: Session, payload: dict):
    installation_id = payload.get("installation", {}).get("id")
    repo_full_name = payload.get("repository", {}).get("full_name")

    if not installation_id or not repo_full_name:
        print("Warning: Missing installation_id or repo_full_name in PR opened payload.")
        return

    repo = (
        db.query(Repository)
        .filter(
            Repository.installation_id == installation_id, Repository.repo_name == repo_full_name
        )
        .first()
    )

    if not repo:
        print(f"Warning: Repository not found: {repo_full_name} (inst: {installation_id})")
        return

    if not repo.is_active:
        print(f"Skipping PR #{payload['number']} for deactivated repository: {repo_full_name}")
        head_sha = payload["pull_request"]["head"]["sha"]
        await create_skipped_check_run(
            repo_full_name,
            head_sha,
            installation_id,
            "Drift analysis is disabled for this repository. Enable it in Delta to resume tracking.",
        )
        return

    # Skip PR analysis for PR raised by Delta
    head_branch_opened = payload["pull_request"]["head"]["ref"]
    if head_branch_opened.startswith("docs/delta-fix/"):
        print(f"Skipping analysis for docs-fix PR #{payload['number']} in {repo_full_name}.")
        head_sha = payload["pull_request"]["head"]["sha"]
        await create_skipped_check_run(
            repo_full_name,
            head_sha,
            installation_id,
            "This PR was auto-generated by Delta to resolve documentation drift. No analysis required.",
        )
        return

    base_branch = payload["pull_request"]["base"]["ref"]
    head_branch = payload["pull_request"]["head"]["ref"]

    # Create a drift event for the PR
    new_event = DriftEvent(
        repo_id=repo.id,
        pr_number=payload["number"],
        base_branch=base_branch,
        head_branch=head_branch,
        base_sha=payload["pull_request"]["base"]["sha"],
        head_sha=payload["pull_request"]["head"]["sha"],
        processing_phase="queued",
        drift_result="pending",
    )
    db.add(new_event)
    db.flush()
    db.refresh(new_event)

    drift_event_id = str(new_event.id)

    # Create a GH check run to show status in PR
    await create_queued_check_run(
        db, drift_event_id, repo_full_name, new_event.head_sha, installation_id
    )

    # Enqueue the drift analysis as a background task
    if drift_event_id and drift_event_id != "None":
        task_queue.enqueue(run_drift_analysis, drift_event_id)
    else:
        print(f"Error: DriftEvent ID is None for PR #{payload['number']} in {repo_full_name}.")

    # Notify the user that the PR has been queued for drift analysis
    installation = (
        db.query(Installation).filter(Installation.installation_id == installation_id).first()
    )
    if installation and installation.user_id:
        create_notification(
            db,
            installation.user_id,
            f"PR #{payload['number']} opened in {repo_full_name} has been received and queued for drift analysis.",
        )


# Handle pr_synchronize webhook event (new commits pushed to open PR)
async def _handle_pr_synchronize(db: Session, payload: dict):
    installation_id = payload.get("installation", {}).get("id")
    repo_full_name = payload.get("repository", {}).get("full_name")
    pr_number = payload.get("number")

    if not installation_id or not repo_full_name or not pr_number:
        print("Warning: Missing fields in PR synchronize payload.")
        return

    repo = (
        db.query(Repository)
        .filter(
            Repository.installation_id == installation_id, Repository.repo_name == repo_full_name
        )
        .first()
    )

    if not repo:
        print(f"Warning: Repository not found: {repo_full_name} (inst: {installation_id})")
        return

    if not repo.is_active:
        print(f"Skipping PR #{pr_number} sync for deactivated repository: {repo_full_name}")
        head_sha = payload["pull_request"]["head"]["sha"]
        await create_skipped_check_run(
            repo_full_name,
            head_sha,
            installation_id,
            "Drift analysis is disabled for this repository. Enable it in Delta to resume tracking.",
        )
        return

    base_branch = payload["pull_request"]["base"]["ref"]
    head_branch = payload["pull_request"]["head"]["ref"]
    new_base_sha = payload["pull_request"]["base"]["sha"]
    new_head_sha = payload["pull_request"]["head"]["sha"]

    # Detecting if this synchronize was triggered by merging Delta's docs-fix PR
    existing_event = (
        db.query(DriftEvent)
        .filter(DriftEvent.repo_id == repo.id, DriftEvent.pr_number == pr_number)
        .order_by(DriftEvent.created_at.desc())
        .first()
    )
    if (
        existing_event
        and existing_event.docs_pr_number
        and existing_event.processing_phase == "fix_pr_raised"
    ):
        try:
            commit = await get_commit(installation_id, repo_full_name, new_head_sha)
            if commit:
                commit_message = commit.get("commit", {}).get("message", "")
                parents = commit.get("parents", [])
                is_merge_commit = len(parents) >= 2
                mentions_docs_pr = f"#{existing_event.docs_pr_number}" in commit_message
                if is_merge_commit and mentions_docs_pr:
                    existing_event.processing_phase = "fix_pr_merged"
                    db.flush()
                    await create_success_check_run(
                        repo_full_name,
                        new_head_sha,
                        installation_id,
                        "Documentation Drift Resolved",
                        f"Delta's documentation fix (PR #{existing_event.docs_pr_number}) was successfully merged. No drift detected.",
                    )
                    return
        except Exception as e:
            print(f"Error detecting docs-fix merge for PR #{pr_number}: {str(e)}")

    # Find the existing drift event for this PR and reset it for re-analysis
    drift_event = (
        db.query(DriftEvent)
        .filter(DriftEvent.repo_id == repo.id, DriftEvent.pr_number == pr_number)
        .order_by(DriftEvent.created_at.desc())
        .first()
    )

    if drift_event:
        # Clear stale findings and code changes from the previous run
        db.query(DriftFinding).filter(DriftFinding.drift_event_id == drift_event.id).delete(
            synchronize_session=False
        )
        db.query(CodeChange).filter(CodeChange.drift_event_id == drift_event.id).delete(
            synchronize_session=False
        )

        # Update the SHAs and reset to a clean queued state
        drift_event.base_sha = new_base_sha
        drift_event.head_sha = new_head_sha
        drift_event.processing_phase = "queued"
        drift_event.drift_result = "pending"
        drift_event.overall_drift_score = None
        drift_event.summary = None
        drift_event.error_message = None
        drift_event.started_at = None
        drift_event.completed_at = None
        drift_event.check_run_id = None
        db.flush()

        drift_event_id = str(drift_event.id)
    else:
        # If no existing event found, then creates a fresh one
        new_event = DriftEvent(
            repo_id=repo.id,
            pr_number=pr_number,
            base_branch=base_branch,
            head_branch=head_branch,
            base_sha=new_base_sha,
            head_sha=new_head_sha,
            processing_phase="queued",
            drift_result="pending",
        )
        db.add(new_event)
        db.flush()
        db.refresh(new_event)
        drift_event_id = str(new_event.id)

    # Create a fresh GH check run
    await create_queued_check_run(db, drift_event_id, repo_full_name, new_head_sha, installation_id)

    # Enqueue drift analysis job
    task_queue.enqueue(run_drift_analysis, drift_event_id)

    # Notify the user that new commits have been detected and drift analysis is re-queued
    installation = (
        db.query(Installation).filter(Installation.installation_id == installation_id).first()
    )
    if installation and installation.user_id:
        create_notification(
            db,
            installation.user_id,
            f"PR #{pr_number} in {repo_full_name} has new commits and has been re-queued for drift analysis.",
        )
